name: Java CI Pipeline - main branch only

on:
  push:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 23 (Eclipse Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Make Maven Wrapper executable
        run: chmod +x ./mvnw

      - name: Install dependencies and run tests + package
        run: ./mvnw clean verify package --batch-mode

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Install Trivy vulnerability scanner
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.67.2/trivy_0.67.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.67.2_Linux-64bit.deb

      - name: Scan Docker image for vulnerabilities
        run: trivy image --scanners vuln --exit-code 0 --severity CRITICAL,HIGH --ignore-unfixed app:latest

      - name: Debug Docker secrets
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          if [ -z "$DOCKER_USER" ]; then echo "DOCKER_USER secret is missing!"; exit 1; else echo "DOCKER_USER secret is set"; fi
          if [ -z "$DOCKER_PASS" ]; then echo "DOCKER_PASS secret is missing!"; exit 1; else echo "DOCKER_PASS secret is set"; fi

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Verify Docker login
        run: docker info

      - name: Tag and push Docker image
        run: |
          docker tag app:latest dileep1506/java-app:latest
          docker push dileep1506/java-app:latest
