name: Java Lint and Trivy Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Java Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Run Checkstyle (allow warnings)
        # ✅ '|| true' prevents Checkstyle failure from stopping the pipeline
        run: ./mvnw checkstyle:check || true

  trivy-scan:
    name: Build Docker & Trivy Scan
    runs-on: ubuntu-latest
    needs: lint  # ✅ Still runs after lint, regardless of warnings

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make Maven Wrapper executable (for Docker build)
        run: chmod +x mvnw

      - name: Build Docker image
        run: docker build -t javaapp:latest .

      - name: Scan filesystem with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-path: .
          format: table
          exit-code: 0
          ignore-unfixed: true

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: javaapp:latest
          format: json
          exit-code: 0
          ignore-unfixed: true

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
